// THE dynamic canonical output contract for Admin Bulk Upload prompts.
//
// SINGLE SOURCE OF TRUTH (Phases 3, 4, 8):
//   Every Admin Bulk Upload prompt — DB-stored, in-code fallback, or the 
//   "Copy System Prompt" shortcut — is composed at display/copy time from a
//   topic prompt plus THIS contract. The contract is generated by the
//   application, versioned via QUESTION_OUTPUT_CONTRACT_VERSION, and never
//   stored inside topic prompts (their format sections hold the marker
//   [PREPAREFORU_DYNAMIC_OUTPUT_CONTRACT] instead).
//
// The contract stays in lock-step with the PRODUCTION parsers:
//   - The visual type enum is imported from src/types/exam.types
//     (SUPPORTED_VISUAL_TYPES) — the same enum the parser switches on.
//   - The size limits are imported from questionVisualSchemas.ts
//     (VISUAL_LIMITS) — the same limits assertVisualSizeLimits enforces.
//   - Every example object built by buildVisualExample / 
//     buildCanonicalQuestionExample is asserted in unit tests to pass the REAL
//     normalizeVisualInput → BulkQuestionSchema → SingleQuestionSchema write
//     chain. If the prompt teaches a shape the parser rejects, tests fail.
//
// The contract deliberately contains NO legacy tokens: no visual_engine, no
// render_type, no bilingual visual keys (title_en/title_te/headers_en/rows_en),
// no separate language-specific visual siblings, no `options`/`correct`
// aliases, no `metadata` wrapper, no `diagram` forms, and no unsupported types.
// Every visual is ONE canonical object whose human-readable text is bilingual
// ("English / Telugu") per the VISUAL LANGUAGE RULE taught below. Tests scan
// BOTH the contract and every FINAL composed prompt (topic body + identity +
// contract) for these tokens.

import { SUPPORTED_VISUAL_TYPES } from '../../types/exam.types'
import type { VisualType } from '../../types/exam.types'
import { VISUAL_LIMITS } from '../../validations/questionVisualSchemas'
import type { CanonicalQuestionVisual } from '../../validations/questionVisualSchemas'

export const QUESTION_OUTPUT_CONTRACT_VERSION = '1.5'

/** Header that makes composeBulkUploadPrompt idempotent (contract present). */
export const CONTRACT_AUTHORITY_PREFIX = 'CANONICAL OUTPUT CONTRACT'
export const CONTRACT_IDEMPOTENCY_RE = new RegExp(`${CONTRACT_AUTHORITY_PREFIX} v\\d+\\.\\d+`)

const VERSION = QUESTION_OUTPUT_CONTRACT_VERSION

// ─────────────────────────────────────────────────────────────────────────────
// Single structure for the canonical question object the AI must emit. The key
// order and naming is exactly what BulkQuestionSchema consumes after normal-
// ization; the Telugu/topic bytes pass through untouched.
// ─────────────────────────────────────────────────────────────────────────────

export const CANONICAL_QUESTION_FIELDS: readonly string[] = [
  '"topic_en" — copy VERBATIM from this prompt (never translate); identifies the Topic GROUP, never a subtopic',
  '"topic_te" — copy VERBATIM from this prompt; null only when the topic has no Telugu',
  '"question_text_en" — the English question',
  '"question_text_te" — Telugu question (REQUIRED when this topic has a Telugu name; null only when the topic has no Telugu)',
  '"option_a_en" / "option_b_en" / "option_c_en" / "option_d_en" — exactly 4 English options, each the BARE answer text with NO "A. " / "B. " / "C. " / "D. " letter prefix (the letter identity is the key suffix)',
  '"option_a_te" / "option_b_te" / "option_c_te" / "option_d_te" — Telugu options (REQUIRED when this topic has a Telugu name); likewise BARE answer text with NO "ఎ. " / "బి. " / "సి. " / "డి. " letter prefix',
  '"correct_option" — the bare uppercase letter "A", "B", "C" or "D": NEVER "B. Canberra", never "Canberra", and never the Telugu letters ఎ./బి./సి./డి.',
  '"explanation_en" — brief explanation why the answer is correct',
  '"explanation_te" — Telugu explanation (REQUIRED when this topic has a Telugu name)',
  '"difficulty" — exactly one of "easy", "medium", "hard"',
  '"visual" — null, or the visual object described in the CANONICAL VISUAL REQUIREMENTS below (include only when the candidate must reason from it)',
]

// ─────────────────────────────────────────────────────────────────────────────
// Visual contract — one spec record per supported type. The prose description
// and the machine-checked example are generated from the SAME record, so the
// prompt can never teach a shape the parser rejects.
// ─────────────────────────────────────────────────────────────────────────────

export interface VisualTypeContract {
  type: VisualType
  dataFields: string
  buildData: () => Record<string, unknown>
}

const TITLE_PATTERN = `"title": "short heading" or null (max ${VISUAL_LIMITS.maxTitleLength} characters)`

// Every example is deliberately BILINGUAL: the ONE canonical visual carries all
// human-readable text as "English / Telugu" (single string, space-slash-space).
// A visual is never duplicated into language-specific siblings. Numbers and
// coordinates stay numeric; Mermaid/SVG/LaTeX syntax and JSON keys are unchanged.
// The table, geometry, svg, and map_overlay examples keep numerical/structural
// values numeric while splitting only language-bearing text; the latex example
// keeps the formula pure (its bilingual text lives in the title).
const BILINGUAL_EXAMPLE_TITLES: Record<VisualType, string> = {
  table: 'Major Rivers / ప్రధాన నదులు',
  chart: 'Crop Production / పంట ఉత్పత్తి',
  geometry: 'Triangle / త్రిభుజం',
  venn: 'Classification / వర్గీకరణ',
  mermaid: 'Parliament Structure / పార్లమెంటు నిర్మాణం',
  latex: 'Quadratic Formula / ద్విఘాత సూత్రం',
  svg: 'River Course / నది మార్గం',
  map_overlay: 'Empire Extent / సామ్రాజ్య విస్తీర్ణం',
}

function vennData(): Record<string, unknown> {
  return { setA: 'Plants / మొక్కలు', setB: 'Animals / జంతువులు', intersection: 'Both / రెండూ' }
}

function chartData(): Record<string, unknown> {
  return {
    chartType: 'bar',
    labels: ['2019', '2020', '2021'],
    series: [{ name: 'Rice / బియ్యం', value: [120, 180, 145] }],
  }
}

function geometryData(): Record<string, unknown> {
  return {
    shape: 'triangle',
    labels: { ab: 'Side AB / భుజం AB', bc: 'Side BC / భుజం BC', angleA: 'Angle A / కోణం A' },
  }
}

function tableData(): Record<string, unknown> {
  return {
    headers: ['River / నది', 'Length (km) / పొడవు (కి.మీ)'],
    rows: [
      ['Godavari / గోదావరి', 1465],
      ['Krishna / కృష్ణా', 1400],
    ],
  }
}

function mermaidData(): Record<string, unknown> {
  return { code: 'graph TD; A[Parliament / పార్లమెంటు] --> B[Lok Sabha / లోక్ సభ]; A --> C[Rajya Sabha / రాజ్యసభ]' }
}

function latexData(): Record<string, unknown> {
  return { expression: 'x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}' }
}

function svgData(): Record<string, unknown> {
  return { svg_content: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 80"><text x="10" y="24" font-size="14" fill="#000">River / నది</text><rect x="10" y="32" width="180" height="30" fill="#dce6f2"/></svg>' }
}

function mapOverlayData(): Record<string, unknown> {
  return {
    center: { lat: 17.385, lng: 78.4867 },
    zoom: 7,
    overlays: [{ lat: 17.385, lng: 78.4867, label: 'Amaravati / అమరావతి', color: '#e31b23' }],
  }
}

const LIMITED = VISUAL_LIMITS

export const VISUAL_TYPE_CONTRACTS: readonly VisualTypeContract[] = [
  {
    type: 'table',
    dataFields:
      `"data": { "headers": ["col A", "col B"], "rows": [ ["value", value], ... ] } — up to ` +
      `${LIMITED.maxTableColumns} columns and ${LIMITED.maxTableRows} rows; cells may be text, numbers, or booleans`,
    buildData: tableData,
  },
  {
    type: 'chart',
    dataFields:
      `"data": { "chartType": "bar" | "line" | "area" | "pie", "labels": [...], "data": [...], "series": [...] } — up to ` +
      `${LIMITED.maxChartPoints} points and ${LIMITED.maxChartSeries} series`,
    buildData: chartData,
  },
  {
    type: 'geometry',
    dataFields:
      `"data": { "shape": "triangle" | "circle", "labels": { "ab", "bc", "angleA" }, "radius": number }` +
      ` — triangle uses labels; circle uses radius`,
    buildData: geometryData,
  },
  {
    type: 'venn',
    dataFields: `"data": { "setA": "label A", "setB": "label B", "intersection": "shared" } — string labels`,
    buildData: vennData,
  },
  {
    type: 'mermaid',
    dataFields:
      `"data": { "code": "mermaid source" } — the complete mermaid source; up to ` +
      `${LIMITED.maxMermaidCodeLength} characters`,
    buildData: mermaidData,
  },
  {
    type: 'latex',
    dataFields:
      `"data": { "expression": "KaTeX expression" } — a non-empty LaTeX/KaTeX expression; up to ` +
      `${LIMITED.maxLatexExpressionLength} characters`,
    buildData: latexData,
  },
  {
    type: 'svg',
    dataFields:
      `"data": { "svg_content": "<svg ...>...</svg>" } — self-contained SVG markup; up to ` +
      `${LIMITED.maxSvgPayloadBytes} bytes`,
    buildData: svgData,
  },
  {
    type: 'map_overlay',
    dataFields:
      `"data": { "center": { "lat": number, "lng": number }, "zoom": 1-20, "overlays": [ { "lat", "lng", "label", "color" } ] } — up to ` +
      `${LIMITED.maxMapOverlays} overlays`,
    buildData: mapOverlayData,
  },
]

/** Build a parse-able canonical visual example for the given supported type. */
export function buildVisualExample(type: VisualType): CanonicalQuestionVisual {
  const spec = VISUAL_TYPE_CONTRACTS.find(s => s.type === type)
  if (!spec) {
    throw new Error(`buildVisualExample: unsupported visual type "${type}"`)
  }
  return { type, title: BILINGUAL_EXAMPLE_TITLES[type], data: spec.buildData() } as CanonicalQuestionVisual
}

export function buildAllVisualExamples(): CanonicalQuestionVisual[] {
  return SUPPORTED_VISUAL_TYPES.map(t => buildVisualExample(t))
}

// ─────────────────────────────────────────────────────────────────────────────
// Example question object builder (teaches the canonical envelope + a visual).
// The returned object MUST pass BulkQuestionSchema (mapped to the DB write
// shape, it must also pass SingleQuestionSchema) — enforced by unit tests.
// The DEFAULT topic values are placeholders, NOT a real topic: the contract is
// topic-neutral and byte-identical for every topic (the live names come from
// the composed TOPIC IDENTITY block placed above the contract). The sample
// question itself is deliberately domain-neutral — it teaches the JSON SHAPE,
// not that any single exam subject is implied by the contract.
// ─────────────────────────────────────────────────────────────────────────────

export function buildCanonicalQuestionExample(
  topicEn = '<COPY topic_en VERBATIM>',
  topicTe: string | null = '<COPY topic_te VERBATIM>',
  visual: CanonicalQuestionVisual | null = null
): Record<string, unknown> {
  return {
    topic_en: topicEn,
    topic_te: topicTe,
    question_text_en: 'Which of the following is the capital of Australia?',
    question_text_te: 'కింది వాటిలో ఆస్ట్రేలియా రాజధాని ఏది?',
    option_a_en: 'Sydney',
    option_a_te: 'సిడ్నీ',
    option_b_en: 'Canberra',
    option_b_te: 'కాన్బెర్రా',
    option_c_en: 'Melbourne',
    option_c_te: 'మెల్బోర్న్',
    option_d_en: 'Perth',
    option_d_te: 'పెర్త్',
    correct_option: 'B',
    explanation_en: 'Canberra is the national capital of Australia.',
    explanation_te: 'కాన్బెర్రా ఆస్ట్రేలియా జాతీయ రాజధాని.',
    difficulty: 'easy',
    visual,
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Prose sections of the contract.
// ─────────────────────────────────────────────────────────────────────────────

function buildQuestionSection(): string {
  const exampleJson = JSON.stringify(buildCanonicalQuestionExample(), null, 2)
  return [
    '',
    '## QUESTION CONTENT REQUIREMENTS',
    '',
    'Return a single JSON array. Every element is ONE question object with EXACTLY these keys:',
    ...CANONICAL_QUESTION_FIELDS.map(f => `- ${f}`),
    '',
    'Example of one question object (without a visual). Replace the two placeholder',
    'topic values below with the EXACT topic names declared in the TOPIC IDENTITY',
    'section above — never reword them:',
    '',
    '```json',
    exampleJson,
    '```',
    '',
    'Every question must be reasoning-based (comparison, chronology, cause/effect,',
    'application, inference, multi-statement reasoning) — never recall-only trivia',
    'and never isolated one-word-fact retrieval. The topic fields identify the',
    'Topic GROUP, never a subtopic.',
    '',
  ].join('\n')
}

function buildBilingualSection(): string {
  return [
    '',
    '## BILINGUAL REQUIREMENTS',
    '',
    'When this topic has a Telugu name (topic_te non-null), EVERY question MUST fill',
    'every Telugu field — question_text_te, option_a_te, option_b_te, option_c_te,',
    'option_d_te and explanation_te — for the ENTIRE batch, with no null Telugu values.',
    'Telugu text is natural, grammatically correct and faithfully preserves',
    'the full meaning; Telugu options mirror their English counterparts exactly and',
    'mathematical/technical terminology is translated accurately.',
    '',
    'When this topic has no Telugu name (topic_te null), the Telugu content fields',
    'may be null or omitted.',
    '',
  ].join('\n')
}

function buildOptionSection(): string {
  return [
    '',
    '## OPTION & ANSWER REQUIREMENTS',
    '',
    'OPTION VALUE RULE — THE LETTER IS NEVER PART OF THE OPTION VALUE',
    'Write every option as the BARE answer text with no leading letter and no',
    'period. The letter identity is carried ONLY by the field-name suffix —',
    'option_a_* is option A, option_b_* is option B, option_c_* is option C,',
    'option_d_* is option D — for ENGLISH and TELUGU alike (option_a_te is',
    'option A, option_b_te is option B, ...). "correct_option" is the bare',
    'uppercase letter "A", "B", "C" or "D".',
    '',
    'Correct:  "option_a_en": "Sydney",  "option_a_te": "సిడ్నీ",  "correct_option": "B"',
    '',
    'Never write "A. Sydney", "ఎ. సిడ్నీ" or "B. Canberra" in option_a_en,',
    'option_a_te or correct_option — prefixed values, bare names in correct_option,',
    'and the Telugu letters ఎ./బి./సి./డి. are all WRONG.',
    '',
    'Exactly 4 options and exactly one correct answer per question. Options stay',
    'similar in length, structure and style. Distractors are the plausible mistakes',
    'real candidates make; obviously wrong or absurd options are rejected. Never',
    '"All of the above", never "None of the above".',
    '',
  ].join('\n')
}

function buildDistributionSection(): string {
  return [
    '',
    '## DIFFICULTY & DISTRIBUTION REQUIREMENTS',
    '',
    'Generate EXACTLY the number of questions the topic instructions specify —',
    'never fewer, never more. Count the array internally and correct the total.',
    '',
    'Convert every percentage/ratio target to INTEGER counts that sum to the required total;',
    'topic coverage, difficulty, cognitive and question-type allocations each sum to',
    'that total and do not conflict.',
    '',
    'difficulty is exactly easy, medium or hard.',
    '',
    'Spread correct answers across A, B, C and D naturally with no repeatable',
    'pattern, covering the sections the topic instructions require.',
    '',
  ].join('\n')
}

function buildVisualSection(): string {
  const typeEnum = SUPPORTED_VISUAL_TYPES.map(t => `"${t}"`).join(' | ')
  const perType = VISUAL_TYPE_CONTRACTS.map(spec => {
    const example = JSON.stringify(buildVisualExample(spec.type), null, 2)
    return [
      `### ${spec.type}`,
      '',
      `${TITLE_PATTERN}`,
      spec.dataFields,
      '',
      '```json',
      example,
      '```',
      '',
    ].join('\n')
  }).join('\n')

  return [
    '',
    '## CANONICAL VISUAL REQUIREMENTS',
    '',
    'A visual is used only when the question genuinely needs a table, chart, timeline, map, formula, or flow to reason correctly.',
    'Every visual object has EXACTLY this envelope:',
    '',
    '```json',
    '{ "type": ' + typeEnum + ', "title": "short heading" | null, "data": { ... } }',
    '```',
    '',
    `Whole visual size must stay under ${LIMITED.maxJsonBytes} bytes with nesting depth up to ${LIMITED.maxDepth}.`,
    '',
    'VISUAL LANGUAGE RULE — ONE VISUAL, BILINGUAL TEXT',
    'Produce EXACTLY ONE visual object per visual-backed question. Never emit a',
    'visual twice in separate language-specific forms, and never pair the visual',
    'with language-suffixed keys. Every human-readable text inside the visual is',
    'written in BOTH languages using a single " / " (space-slash-space) separator,',
    'e.g.:',
    '',
    '"title": "Population Growth / జనాభా పెరుగుదల"',
    '',
    'Apply the separator to the visual title, table headers, table text cells,',
    'chart axis labels, chart series names, map overlay labels, Venn labels,',
    'geometry labels, SVG text nodes, and Mermaid node and edge labels.',
    '',
    'Leave all structural content untouched: JSON keys, Mermaid/SVG/LaTeX syntax,',
    'numeric values, coordinates and colors keep their exact form — numbers stay',
    'numbers. A purely numeric or language-neutral value (e.g. a year "2020" or an',
    'angle "60°") is written once with no separator; only genuinely',
    'language-bearing text (words, names, units) is split with " / " between the',
    'English and Telugu versions.',
    '',
    'Bilingual table headers are written exactly like this — one header string per',
    'column, each carrying its own " / " separator:',
    '  `"headers": ["Region / \u0C2A\u0C4D\u0C30\u0C3E\u0C02\u0C24\u0C02", "Population / \u0C1C\u0C28\u0C3E\u0C2D\u0C3E", "Year / \u0C38\u0C02\u0C35\u0C24\u0C4D\u0C38\u0C30\u0C02"]`',
    'Never fake a bilingual value: a purely numeric cell, coordinate or year is',
    'written once ("10", "60\u00B0", "2020") \u2014 never duplicated as "10 / 10" or',
    '"60 / 60". The separator splits ONLY genuinely language-bearing text, and a',
    'score, percentage or value presented in two languages is a grading mistake.',
    '',
    'Per-type data shape:',
    '',
    perType,
    '',
    'VISUAL QUESTION — EVIDENCE, NOT ANSWER',
    'A visual question is a WORKSPACE problem, not a reading problem. The visual is',
    'EVIDENCE the candidate reasons with — the answer is derived, never a value that',
    'sits visibly on the visual. If removing the visual leaves the question answerable',
    'from ordinary text or general knowledge, the visual is decorative and must not be',
    'generated.',
    '',
    'MANDATORY VISUAL QUESTION RULES — every visual question satisfies all ten:',
    '1. EVIDENCE FIRST — the visual supplies information the reasoning genuinely needs;',
    '   it behaves like a real data table or map in an exam paper.',
    '2. THE VISUAL IS THE WORKSPACE — the candidate works ON the visual (inspects,',
    '   compares, calculates or derives) to arrive at the answer.',
    '3. THE VISUAL IS THE AUTHORITY — the values reasoned over come from the visual,',
    '   not from unstated background knowledge.',
    '4. THE QUESTION MUST REFERENCE THE VISUAL — the question text points to the',
    '   visual and names what the candidate must do with it.',
    '5. THE ANSWER MUST BE UNOBTAINABLE WITHOUT THE VISUAL — a candidate who ignores',
    '   the visual cannot answer confidently.',
    '6. THE ANSWER MUST BE OBTAINABLE FROM THE VISUAL ALONE — nothing outside the',
    '   visual is required to solve the question.',
    '7. THE VISUAL MUST NEVER REVEAL THE ANSWER — no label, cell, shape, colour or',
    '   position in the visual hands out the answer by itself.',
    '8. THE VISUAL MUST NEVER CONTAIN THE ANSWER — RAW, LABELLED, OR AS A DERIVED',
    '   FACT: the answer never appears anywhere in the visual.',
    '9. THE VISUAL MUST NEVER REPEAT THE QUESTION TEXT — a visual that restates the',
    '   question or an option is empty ceremony.',
    '10. THE ANSWER MUST NEVER BE THE "OBVIOUS VISUAL READ" — if the correct option is',
    '    the only pattern that stands out, the design is wrong; rework the visual so',
    '    the candidate must reason to the answer.',
    '',
    'ACCEPTABLE OPERATIONS ON A VISUAL — a visual-backed question legitimately tests',
    'calculation, comparison, percentage, ratio, trend, inference, classification,',
    'relationship, spatial reasoning, chronological reasoning, multi-step derivation',
    'and combining several visual elements. Direct-lookup shapes (an answer read from',
    'a single label, cell or marked point) are NOT acceptable — such visuals must not',
    'be generated.',
    '',
    'DO NOT OVERRESTRICT VISUALS',
    'A necessary visual is welcome, never penalized. The rules forbid ONLY decorative',
    'and answer-revealing visuals; they never forbid a genuinely reasoning-based',
    'visual and never demand that a batch avoid or minimise visuals. When the candidate',
    'must truly reason from a visual, generate it. Visual-coverage guidance inside the',
    'topic instructions is a target, not a ceiling — and never a licence for decorative',
    'visuals.',
    '',
    'VISUAL USE — REASONING EXAMPLES',
    'Good table: several sites/entities with multiple attributes; the question asks which',
    'conclusion, difference or ordering is best supported by comparing the rows/columns.',
    'Good chart: values whose percentage, difference, ratio or trend must be derived',
    'before an option can be chosen — the answer is never a chart label read directly.',
    'Good map: locations shown WITHOUT labelling the conclusion; the candidate infers the',
    'historical/geographic interpretation from the distribution. Good chronology: events',
    'and dates in a table; the candidate identifies a sequence or an interval.',
    '',
    'VISUAL TYPE SELECTION',
    'Choose the type that fits the reasoning (table, chart, map_overlay, geometry, venn,',
    'mermaid, latex or svg). Follow the visual opportunities named in the topic',
    'instructions; do NOT force svg, latex, geometry or venn merely because they are',
    'supported. A high-quality question without a visual beats a forced visual question.',
    '',
    'VISUAL EXPLANATION',
    'For a visual question, the explanation MUST state which information from the visual',
    'was used and how it leads to the answer. Never write "the visual shows the answer" —',
    'explain the comparison, calculation or inference instead.',
    '',
  ].join('\n')
}

function buildGoodBadExamplesSection(): string {
  return [
    '',
    '## GOOD / BAD VISUAL EXAMPLES',
    '',
    'GOOD VISUAL QUESTION EXAMPLES — the visual is EVIDENCE; the answer comes from reasoning:',
    '',
    'GOOD 1 — TABLE OF POPULATION CHANGE',
    'Question: Which region shows the highest percentage growth in population between',
    'the two census years?',
    '```json',
    '{',
    '  "type": "table",',
    '  "title": "Regional Population / ప్రాంతీయ జనాభా",',
    '  "data": {',
    '    "headers": ["Region / ప్రాంతం", "2001", "2011"],',
    '    "rows": [',
    '      ["A / ఎ", 100, 150],',
    '      ["B / బి", 200, 240],',
    '      ["C / సి", 300, 330]',
    '    ]',
    '  }',
    '}',
    '```',
    'Why it works: the answer requires computing each region\'s percentage change from',
    'the two displayed columns; no region name is the answer.',
    '',
    'GOOD 2 — CHART OF A PRODUCTION TREND',
    'Question: Rice production in 2021 is approximately what percentage of the 2019',
    'level?',
    '```json',
    '{',
    '  "type": "chart",',
    '  "title": "Rice Production / వరి ఉత్పత్తి",',
    '  "data": {',
    '    "chartType": "bar",',
    '    "labels": ["2019", "2020", "2021"],',
    '    "series": [{ "name": "Rice / బియ్యం", "value": [120, 180, 145] }]',
    '  }',
    '}',
    '```',
    'Why it works: the answer needs the ratio of two displayed values; the answer is',
    'never a chart label read directly.',
    '',
    'GOOD 3 — MAP OF MARKED TOWNS',
    'Question: Which marked town lies closest to the midpoint of the route between',
    'Nagpur and Ranchi?',
    '```json',
    '{',
    '  "type": "map_overlay",',
    '  "title": "Trade Route Towns / వాణిజ్య మార్గ పట్టణాలు",',
    '  "data": {',
    '    "center": { "lat": 21.6, "lng": 81.5 },',
    '    "zoom": 6,',
    '    "overlays": [',
    '      { "lat": 21.0, "lng": 79.0, "label": "Nagpur / నాగ్పూర్", "color": "#e31b23" },',
    '      { "lat": 18.5, "lng": 78.0, "label": "Hyderabad / హైదరాబాద్", "color": "#e31b23" },',
    '      { "lat": 22.3, "lng": 84.0, "label": "Ranchi / రాంచీ", "color": "#e31b23" },',
    '      { "lat": 21.5, "lng": 82.0, "label": "Raipur / రాయ్పూర్", "color": "#e31b23" }',
    '    ]',
    '  }',
    '}',
    '```',
    'Why it works: the candidate compares marked positions on the map; the map never',
    'states which town was chosen.',
    '',
    'GOOD 4 — MERMAID FLOW OF A PROCESS',
    'Question: According to the shown flow, which stage immediately follows the Rajya',
    'Sabha review?',
    '```json',
    '{',
    '  "type": "mermaid",',
    '  "title": "Bill Passage Sequence / బిల్లు ఆమోద క్రమం",',
    '  "data": {',
    '    "code": "graph TD; A[Bill Introduction / బిల్లు ప్రవేశం] --> B[Lok Sabha Debate / లోక్ సభ చర్చ]; B --> C[Rajya Sabha Review / రాజ్యసభ సమీక్ష]; C --> D[Presidential Assent / రాష్ట్రపతి ఆమోదం]; D --> E[Law / చట్టం]"',
    '  }',
    '}',
    '```',
    'Why it works: the answer is read from the edges between the named stages; the',
    'candidate traces the sequence instead of reading an answer off a label.',
    '',
    'BAD VISUAL QUESTION EXAMPLES — DO NOT GENERATE',
    'BAD 1 — OBVIOUS IDENTIFICATION: a map with one marked dot labelled "New Delhi"',
    'whose question asks "Which city is marked?" — the label IS the answer.',
    '',
    'BAD 2 — RANK LIST LEAKAGE: a ranked "Top 5 Population Countries" bar list whose',
    'question asks for the rank — the answer is the chart label read directly.',
    '',
    'BAD 3 — DIRECT-ANSWER CELL: a table of rulers with a "Dynasty" column whose',
    'question asks "To which dynasty does Ashoka belong?" — the answer is a table cell',
    'read directly.',
    '',
    'BAD 4 — QUESTION TEXT REPETITION: a visual that merely restates the question text',
    'or re-prints an option inside a labelled box.',
    '',
    'BAD 5 — TITLE REVEALS THE ANSWER: a chart titled "State with the Highest Coal',
    'Reserves" whose question asks exactly that — the title gives the answer away.',
    '',
    'BAD 6 — OBVIOUS READ: a Venn whose asked overlap is the only coloured region,',
    'with the question "Which region represents members of both sets?"',
    '',
    'BAD 7 — DECORATIVE FLOW: a mermaid chain (A to B to C) that merely restates a',
    'process the question text already describes — the candidate answers without ever',
    'reading the flow, so the visual is decorative and must not be generated.',
    '',
  ].join('\n')
}

function buildAnswerLeakSection(): string {
  return [
    '',
    '## VISUAL ANSWER-LEAK PREVENTION',
    '',
    'A visual must never hand over or hint at the answer — directly, implicitly, or',
    'through any indicator:',
    '1. NO ANSWER TEXT — the answer never appears in the visual as raw text, a labelled',
    '   value, or a derived fact (Rule 8 above).',
    '2. NO ANSWER INDICATOR — the visual contains no "Correct Answer", "Answer",',
    '   "Option A/B/C/D" or similar marker anywhere: not in the title, a label, a cell,',
    '   a highlighted row, a colour, a map marker, or a tooltip. A visual whose single',
    '   highlighted entry is itself the answer is an answer leak.',
    '3. NO OBVIOUS READ — the correct option is never the only pattern that stands out;',
    '   if it is, rework the visual so the candidate must reason to the answer.',
    '4. NO QUESTION/OPTION REPETITION — the visual never restates the question or',
    '   re-prints an option.',
    '5. NO RANK-LIST LEAK — never ask for a rank or name that is literally displayed',
    '   (a ranked "Top 5 Population Countries" list whose answer is the chart label).',
    '6. NO DIRECT-LOOKUP SHAPE — never generate a visual whose answer is a single cell,',
    '   label or marked point read directly.',
    '',
    'PHASE 7 (VISUAL VALIDATION) re-checks answer-leak safety on the whole set before',
    'the STRICT PASS CONDITION can hold.',
    '',
  ].join('\n')
}

function buildSelfVerificationSection(): string {
  return [
    '',
    '## ITERATIVE SELF-VERIFICATION ENGINE',
    '',
    'Before returning, run EVERY phase below against the working draft. A phase either',
    'passes or it is fixed and re-run; never ship a draft with a failed phase. The',
    'engine proves the output only after PHASE 11 certifies the STRICT PASS CONDITION.',
    '',
    'PHASE 1 — GENERATE',
    'Produce the complete output for this topic in one pass:',
    '- topic_en / topic_te copied VERBATIM from the TOPIC IDENTITY block, identifying',
    '  the Topic GROUP, never a subtopic.',
    '- Reasoning-based questions — comparison, chronology, cause/effect, application,',
    '  inference, multi-statement — never recall-only trivia.',
    '- Exactly 4 options and exactly one correct answer, with three plausible distractors.',
    '',
    'PHASE 2 — INDEPENDENT FULL VERIFICATION',
    'FIRST solve every question before validating anything else: for each question,',
    'cover the "correct_option" value and reason to the answer from the question text,',
    'the visual and the explanation ALONE. NEVER use correct_option as evidence — if',
    'you cannot independently derive the letter you chose, the question is defective',
    'and must be fixed in PHASE 9.',
    'Then run the FULL 18-POINT CHECKLIST over the ENTIRE batch:',
    '1. Exactly 4 options per question: option_a through option_d, English and Telugu.',
    '2. Every question has EXACTLY one correct answer; the three distractors are',
    '   clearly wrong and independent of the explanation.',
    '3. No omnibus options — no option that claims to combine or reject the others;',
    '   each option is one concrete answer.',
    '4. Options are similar in length, structure and style; distractors are the',
    '   plausible mistakes real candidates make, never absurd filler.',
    '5. No option value carries a letter prefix ("A. ...", "ఎ. ...") — the letter',
    '   lives only in the field-name suffix.',
    '6. correct_option is the bare uppercase letter A, B, C or D — never a full',
    '   value, never a Telugu letter.',
    '7. Every question is reasoning-based (comparison, chronology, cause/effect,',
    '   application, inference, multi-statement) — no recall-only trivia, no',
    '   isolated one-word-fact retrieval.',
    '8. Chronology questions arrange events in chronological order where applicable.',
    '9. topic_en and topic_te are byte-identical to the TOPIC IDENTITY values across',
    '   the whole batch — never a subtopic, event, person or region name.',
    '10. Full bilingual completeness: when topic_te is non-null, every question fills',
    '    question_text_te, option_a_te through option_d_te and explanation_te.',
    '11. Neither the question wording, the options, the visual nor the explanation',
    '    reveals the answer.',
    '12. Every visual is evidence: necessary (removal makes the question unanswerable),',
    '    sufficient (the visual alone suffices) and never decorative.',
    '13. No direct-lookup or reading-problem visual — the candidate must inspect,',
    '    compare, calculate, infer, sequence, classify or locate FROM the visual.',
    '14. No visual contains or labels the answer and no visual carries an answer',
    '    indicator ("Correct Answer", "Answer", "Option A/B/C/D").',
    '15. The count, difficulty, question-type, cognitive and coverage allocations',
    '    match the topic targets as integer counts summing to the total.',
    '16. Every mandated section or area from the topic instructions is represented.',
    '17. The concept ledger is clean — no two questions test the same fact, concept,',
    '    relationship, chronology, inference or comparison (even reworded).',
    '18. The whole draft parses as ONE valid JSON array — no trailing or missing',
    '    commas, no markdown code fences, no extra commentary around it.',
    '',
    'PHASE 3 — STRUCTURE VALIDATION',
    '- Every object uses EXACTLY the canonical keys in canonical order taught in the',
    '  QUESTION CONTENT REQUIREMENTS: no aliases, no extra keys, and no database',
    '  fields (exam_id, paper_id, subject_name, created_by).',
    '- correct_option is exactly one of A, B, C or D.',
    '- difficulty is constrained to the canonical easy / medium / hard enum.',
    '- The draft is ONE valid JSON array with nothing before or after it.',
    '',
    'PHASE 4 — TOPIC IDENTITY VALIDATION',
    '- topic_en matches the TOPIC IDENTITY block EXACTLY — byte-for-byte, character',
    '  for character, in every question.',
    '- topic_te matches the TOPIC IDENTITY block EXACTLY (or null when the topic has',
    '  no Telugu name).',
    '- The topic fields identify the Topic GROUP and are never replaced by a',
    '  subtopic, event, person or region name.',
    '- The two values are byte-identical across the entire batch.',
    '',
    'PHASE 5 — DISTRIBUTION VALIDATION',
    '- The total count equals the topic-specified count — never fewer, never more.',
    '- Every percentage/ratio target is converted to INTEGER counts that sum to the',
    '  required total; topic coverage, difficulty, cognitive and question-type',
    '  allocations each sum to that total and do not conflict.',
    '- Correct answers spread across A, B, C and D with no repeatable pattern.',
    '',
    'PHASE 6 — DUPLICATE VALIDATION',
    '- Two questions testing the same fact, concept, relationship, chronology,',
    '  inference or comparison (even if reworded) are duplicates.',
    '- Keep an internal concept ledger; for each duplicate keep the stronger question',
    '  and remove the weaker copy, then re-verify the count in PHASE 5.',
    '',
    'PHASE 7 — VISUAL VALIDATION',
    'Run the VISUAL QUESTION SELF-CHECK — the full A-I battery — on EVERY visual:',
    'A. NECESSITY (REMOVE TEST): if the question can still be answered confidently',
    '   from ordinary factual knowledge alone, the visual is unnecessary: set visual = null.',
    'B. SUFFICIENCY: the visual alone supplies everything the candidate needs to solve.',
    'C. NO DIRECT-ANSWER REVEAL: the visual must not directly display the answer.',
    'D. MEANINGFUL REASONING (INTERPRETATION TEST): the candidate must inspect, compare, calculate, infer,',
    '   sequence, classify or locate FROM the visual to solve;',
    '   a direct-lookup or reading-problem visual is not generated.',
    'E. ANSWER-LEAK (ANSWER-LEAK TEST): nothing in the visual — title, label, cell, row,',
    '   colour, marker or tooltip — leaks the answer or an answer indicator. A ranked',
    '   list whose question asks for the rank is an answer leak; a visual whose single',
    '   highlighted entry is the answer is another.',
    'F. NOT DECORATIVE: A decorative visual is never acceptable. Every visual must be',
    '   educationally meaningful; quality beats quantity, and a batch needs no',
    '   predetermined number of visuals.',
    'G. CANONICAL SCHEMA: the visual object matches the CANONICAL VISUAL REQUIREMENTS',
    '   envelope, its type-specific contract and the size/depth limits of this section.',
    'H. BILINGUAL TEXT: every human-readable visual text follows the VISUAL LANGUAGE',
    '   RULE — "English / Telugu" with a single " / " separator; numbers, coordinates',
    '   and years stay numeric and are never duplicated in a "10 / 10" style.',
    'I. EXACTLY ONE VISUAL: one canonical visual object per visual question — never',
    '   language-sibling objects, never a second copy of the same visual.',
    '',
    'PHASE 8 — ERROR REPORT',
    '- Collect every defect the verification phases found, each tagged to the exact',
    '  element it belongs to — question index, field, or visual property. The error',
    '  report is INTERNAL: it is never returned, never printed, and never present in',
    '  the output.',
    '',
    'PHASE 9 — MINIMAL REFINEMENT',
    '- Repair ONLY the defects PHASE 8 reported, each at its source — inside the',
    '  element it belongs to. Preserve every element that already passes byte-for-byte.',
    '- If one element keeps failing, remove it and insert a clean equivalent so the',
    '  exact count, distributions and coverage of PHASE 5 are still met.',
    '',
    'PHASE 10 — COMPLETE RE-VERIFICATION',
    '- After every repair cycle, re-run EVERY verification phase (2 through 7) over the',
    '  ENTIRE set — not just the repaired elements — and re-check the count,',
    '  distributions, concept ledger and JSON validity of the final array.',
    '',
    'PHASE 11 — ITERATE',
    '- Loop PHASES 8-10 until every phase passes and the STRICT PASS CONDITION holds.',
    '- Allow at most 5 iterations total; a fresh generation does not reset the counter.',
    '- If the output still has an unresolved failure after 5 iterations, NEVER claim',
    '  PASS: return only the best result that satisfies the non-negotiable core — one',
    '  valid JSON array, canonical keys, complete structure and the exact topic count.',
    '- Close the engine with the closing tag below; the engine runs to completion',
    '  exactly once per topic:',
    '',
    '<ITERATIVE_SELF_VERIFICATION_ENGINE>',
    '',
    '## STRICT PASS CONDITION',
    '',
    'The output PASSES the engine only when ALL of the following are true:',
    '- the response is ONE valid JSON array and nothing else (see FINAL OUTPUT RULE);',
    '- every object uses the canonical keys in canonical order, with no aliases and',
    '  no database fields;',
    '- topic_en and topic_te are byte-identical to the TOPIC IDENTITY block;',
    '- the total count equals the topic-specified count and every distribution is',
    '  satisfied with INTEGER counts summing to the total;',
    '- every Telugu topic is fully bilingual — every Telugu field is filled for every',
    '  question, none left null;',
    '- the concept ledger is clean — no two questions test the same concept;',
    '- every visual passes the full A-I self-check; none is decorative,',
    '  answer-revealing or answer-indicating;',
    '- option values carry NO letter prefixes such as "A." or "\u0c0e." and',
    '  correct_option is the bare uppercase letter;',
    '- the answers spread across A/B/C/D with no repeatable pattern;',
    '- no unsupported claims are made in question text, options, visual labels or',
    '  explanation.',
    '',
    '## FAILURE HANDLING',
    '',
    '- A defect is repaired inside the element that caused it, and the affected phases',
    '  are re-run. The repair history is never revealed: the AI returns only the final',
    '  corrected JSON array.',
    '- If the same defect survives a repair, the offending element is removed.',
    '- The engine stops after 5 iterations and returns the best result that fully',
    '  passes; it never returns invalid JSON, never returns conversational text, and',
    '  never returns an uncounted array.',
    '',
    '## PRIORITY ORDER',
    '',
    'When guidance conflicts, apply in this order:',
    '1. HARD SYSTEM CONSTRAINTS — JSON-valid parseable output; canonical envelope,',
    '   keys and enums; canonical visual shapes and size/depth limits; no database',
    '   fields; no option-letter prefixes.',
    '2. THE CONTRACT GATES ABOVE — the ENGINE phases, STRICT PASS CONDITION, FAILURE',
    '   HANDLING and FINAL OUTPUT RULE are absolute and overrule every delegation.',
    '3. EXPLICITLY AUTHORITATIVE TOPIC CONTENT — topic scope, coverage sections,',
    '   mandated count and required distributions.',
    '4. TOPIC IDENTITY AUTHORITY — topic_en/topic_te byte-identical to the TOPIC',
    '   IDENTITY block, never a subtopic.',
    '5. BILINGUAL MANDATE — full Telugu completeness for Telugu-named topics; no',
    '   Telugu field is ever left empty.',
    '6. VISUAL-EVIDENCE RULE — a visual must be necessary and sufficient; the answer',
    '   is never the "obvious visual read" and never directly displayed.',
    '7. OPTION & ANSWER INTEGRITY — one correct answer, three plausible distractors,',
    '   explanation justifying exactly that answer.',
    '8. DUPLICATE PREVENTION — the concept ledger stays clean.',
    '9. COUNT & DISTRIBUTION — integer counts sum correctly to the topic total;',
    '   answer spread is natural.',
    '10. QUALITY & STYLE — reasoning beats recall; plain, professional language.',
    '',
    '## FINAL OUTPUT RULE',
    '',
    'The ONLY thing returned for a topic is the JSON array. No markdown wrappers (triple',
    'backtick blocks), no JSON wrapper, no headings, no notes, no explanations, no',
    'cautionary text, no verification commentary, and never a key-name list outside',
    'the JSON array. The engine is invisible in the output; the uploader accepts ONLY',
    'the bare array.',
    '',
  ].join('\n')
}

/** Compose the full canonical output contract block appended to topic prompts.
 *  Module-level memoized: the contract describes static system data. */
let cachedContract: string | null = null
export function buildCanonicalOutputContract(): string {
  if (cachedContract !== null) return cachedContract
  const contract = [
    '======================================================================',
    `${CONTRACT_AUTHORITY_PREFIX} v${VERSION} \u2014 AUTHORITY`,
    '======================================================================',
    '',
    'The topic instructions above define WHAT to generate. This section is the ONLY',
    'authority for HOW the output must be shaped. If the topic instructions above',
    'embed any other JSON schema, alias names, or visual shape, IGNORE that guidance:',
    'the keys, enums, and visual shapes in THIS section are the only ones accepted',
    'by the uploader.',
    buildQuestionSection(),
    buildBilingualSection(),
    buildOptionSection(),
    buildDistributionSection(),
    buildVisualSection(),
    buildGoodBadExamplesSection(),
    buildAnswerLeakSection(),
    buildSelfVerificationSection(),
  ].join('\n')
  cachedContract = contract
  return contract
}

export interface ComposedContractInfo {
  text: string
  version: string
  visualTypes: readonly string[]
}

export function describeCanonicalOutputContract(): ComposedContractInfo {
  return {
    text: buildCanonicalOutputContract(),
    version: VERSION,
    visualTypes: SUPPORTED_VISUAL_TYPES,
  }
}