// THE dynamic canonical output contract for Admin Bulk Upload prompts.
//
// SINGLE SOURCE OF TRUTH (Phases 3, 4, 8):
//   Every Admin Bulk Upload prompt — DB-stored, in-code fallback, or the 
//   "Copy System Prompt" shortcut — is composed at display/copy time from a
//   topic prompt plus THIS contract. The contract is generated by the
//   application, versioned via QUESTION_OUTPUT_CONTRACT_VERSION, and never
//   stored inside topic prompts (their format sections hold the marker
//   [PREPAREFORU_DYNAMIC_OUTPUT_CONTRACT] instead).
//
// The contract stays in lock-step with the PRODUCTION parsers:
//   - The visual type enum is imported from src/types/exam.types
//     (SUPPORTED_VISUAL_TYPES) — the same enum the parser switches on.
//   - The size limits are imported from questionVisualSchemas.ts
//     (VISUAL_LIMITS) — the same limits assertVisualSizeLimits enforces.
//   - Every example object built by buildVisualExample / 
//     buildCanonicalQuestionExample is asserted in unit tests to pass the REAL
//     normalizeVisualInput → BulkQuestionSchema → SingleQuestionSchema write
//     chain. If the prompt teaches a shape the parser rejects, tests fail.
//
// The contract deliberately contains NO legacy tokens: no visual_engine, no
// render_type, no bilingual visual keys (title_en/title_te/headers_en/rows_en),
// no `options`/`correct` aliases, no `metadata` wrapper, no `diagram` forms,
// and no unsupported types. Tests scan BOTH the contract and every FINAL
// composed prompt (topic body + identity + contract) for these tokens.

import { SUPPORTED_VISUAL_TYPES } from '../../types/exam.types'
import type { VisualType } from '../../types/exam.types'
import { VISUAL_LIMITS } from '../../validations/questionVisualSchemas'
import type { CanonicalQuestionVisual } from '../../validations/questionVisualSchemas'

export const QUESTION_OUTPUT_CONTRACT_VERSION = '1.0'

/** Header that makes composeBulkUploadPrompt idempotent (contract present). */
export const CONTRACT_AUTHORITY_PREFIX = 'CANONICAL OUTPUT CONTRACT'
export const CONTRACT_IDEMPOTENCY_RE = new RegExp(`${CONTRACT_AUTHORITY_PREFIX} v\\d+\\.\\d+`)

const VERSION = QUESTION_OUTPUT_CONTRACT_VERSION

// ─────────────────────────────────────────────────────────────────────────────
// Single structure for the canonical question object the AI must emit. The key
// order and naming is exactly what BulkQuestionSchema consumes after normal-
// ization; the Telugu/topic bytes pass through untouched.
// ─────────────────────────────────────────────────────────────────────────────

export const CANONICAL_QUESTION_FIELDS: readonly string[] = [
  '"topic_en" — copy VERBATIM from this prompt (never translate); identifies the Topic GROUP, never a subtopic',
  '"topic_te" — copy VERBATIM from this prompt; null only when the topic has no Telugu',
  '"question_text_en" — the English question',
  '"question_text_te" — Telugu question (REQUIRED when this topic has a Telugu name; null only when the topic has no Telugu)',
  '"option_a_en" / "option_b_en" / "option_c_en" / "option_d_en" — exactly 4 English options',
  '"option_a_te" / "option_b_te" / "option_c_te" / "option_d_te" — Telugu options (REQUIRED when this topic has a Telugu name)',
  '"correct_option" — exactly one of "A", "B", "C", "D" (uppercase letter)',
  '"explanation_en" — brief explanation why the answer is correct',
  '"explanation_te" — Telugu explanation (REQUIRED when this topic has a Telugu name)',
  '"difficulty" — exactly one of "easy", "medium", "hard"',
  '"visual" — null, or the visual object described in the VISUAL CONTRACT below (include only when the candidate must reason from it)',
]

// ─────────────────────────────────────────────────────────────────────────────
// Visual contract — one spec record per supported type. The prose description
// and the machine-checked example are generated from the SAME record, so the
// prompt can never teach a shape the parser rejects.
// ─────────────────────────────────────────────────────────────────────────────

export interface VisualTypeContract {
  type: VisualType
  dataFields: string
  buildData: () => Record<string, unknown>
}

const TITLE_PATTERN = `"title": "short heading" or null (max ${VISUAL_LIMITS.maxTitleLength} characters)`

function vennData(): Record<string, unknown> {
  return { setA: 'Group A', setB: 'Group B', intersection: 'Shared element' }
}

function chartData(): Record<string, unknown> {
  return {
    chartType: 'bar',
    labels: ['2019', '2020', '2021'],
    data: [120, 180, 145],
  }
}

function geometryData(): Record<string, unknown> {
  return {
    shape: 'triangle',
    labels: { ab: '5 cm', bc: '7 cm', angleA: '60°' },
  }
}

function tableData(): Record<string, unknown> {
  return {
    headers: ['Year', 'Production (tonnes)'],
    rows: [['2020', 1420], ['2021', 1580], ['2022', 1695]],
  }
}

function mermaidData(): Record<string, unknown> {
  return { code: 'graph TD; A[Parliament] --> B[Lok Sabha]; A --> C[Rajya Sabha]' }
}

function latexData(): Record<string, unknown> {
  return { expression: 'x^2 + y^2 = r^2' }
}

function svgData(): Record<string, unknown> {
  return { svg_content: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 50"><rect x="10" y="10" width="80" height="30" fill="#ccc"/></svg>' }
}

function mapOverlayData(): Record<string, unknown> {
  return {
    center: { lat: 17.385, lng: 78.4867 },
    zoom: 7,
    overlays: [{ lat: 17.385, lng: 78.4867, label: 'Hyderabad', color: '#e31b23' }],
  }
}

const LIMITED = VISUAL_LIMITS

export const VISUAL_TYPE_CONTRACTS: readonly VisualTypeContract[] = [
  {
    type: 'table',
    dataFields:
      `"data": { "headers": ["col A", "col B"], "rows": [ ["value", value], ... ] } — up to ` +
      `${LIMITED.maxTableColumns} columns and ${LIMITED.maxTableRows} rows; cells may be text, numbers, or booleans`,
    buildData: tableData,
  },
  {
    type: 'chart',
    dataFields:
      `"data": { "chartType": "bar" | "line" | "area" | "pie", "labels": [...], "data": [...], "series": [...] } — up to ` +
      `${LIMITED.maxChartPoints} points and ${LIMITED.maxChartSeries} series`,
    buildData: chartData,
  },
  {
    type: 'geometry',
    dataFields:
      `"data": { "shape": "triangle" | "circle", "labels": { "ab", "bc", "angleA" }, "radius": number }` +
      ` — triangle uses labels; circle uses radius`,
    buildData: geometryData,
  },
  {
    type: 'venn',
    dataFields: `"data": { "setA": "label A", "setB": "label B", "intersection": "shared" } — string labels`,
    buildData: vennData,
  },
  {
    type: 'mermaid',
    dataFields:
      `"data": { "code": "mermaid source" } — the complete mermaid source; up to ` +
      `${LIMITED.maxMermaidCodeLength} characters`,
    buildData: mermaidData,
  },
  {
    type: 'latex',
    dataFields:
      `"data": { "expression": "KaTeX expression" } — a non-empty LaTeX/KaTeX expression; up to ` +
      `${LIMITED.maxLatexExpressionLength} characters`,
    buildData: latexData,
  },
  {
    type: 'svg',
    dataFields:
      `"data": { "svg_content": "<svg ...>...</svg>" } — self-contained SVG markup; up to ` +
      `${LIMITED.maxSvgPayloadBytes} bytes`,
    buildData: svgData,
  },
  {
    type: 'map_overlay',
    dataFields:
      `"data": { "center": { "lat": number, "lng": number }, "zoom": 1-20, "overlays": [ { "lat", "lng", "label", "color" } ] } — up to ` +
      `${LIMITED.maxMapOverlays} overlays`,
    buildData: mapOverlayData,
  },
]

/** Build a parse-able canonical visual example for the given supported type. */
export function buildVisualExample(type: VisualType): CanonicalQuestionVisual {
  const spec = VISUAL_TYPE_CONTRACTS.find(s => s.type === type)
  if (!spec) {
    throw new Error(`buildVisualExample: unsupported visual type "${type}"`)
  }
  return { type, title: 'Example', data: spec.buildData() } as CanonicalQuestionVisual
}

export function buildAllVisualExamples(): CanonicalQuestionVisual[] {
  return SUPPORTED_VISUAL_TYPES.map(t => buildVisualExample(t))
}

// ─────────────────────────────────────────────────────────────────────────────
// Example question object builder (teaches the canonical envelope + a visual).
// The returned object MUST pass BulkQuestionSchema (mapped to the DB write
// shape, it must also pass SingleQuestionSchema) — enforced by unit tests.
// The DEFAULT topic values are placeholders, NOT a real topic: the contract is
// topic-neutral and byte-identical for every topic (the live names come from
// the composed TOPIC IDENTITY block placed above the contract). The sample
// question itself is deliberately domain-neutral — it teaches the JSON SHAPE,
// not that any single exam subject is implied by the contract.
// ─────────────────────────────────────────────────────────────────────────────

export function buildCanonicalQuestionExample(
  topicEn = '<COPY topic_en VERBATIM>',
  topicTe: string | null = '<COPY topic_te VERBATIM>',
  visual: CanonicalQuestionVisual | null = null
): Record<string, unknown> {
  return {
    topic_en: topicEn,
    topic_te: topicTe,
    question_text_en: 'Which of the following is the capital of Australia?',
    question_text_te: 'కింది వాటిలో ఆస్ట్రేలియా రాజధాని ఏది?',
    option_a_en: 'A. Sydney',
    option_a_te: 'ఎ. సిడ్నీ',
    option_b_en: 'B. Canberra',
    option_b_te: 'బి. కాన్బెర్రా',
    option_c_en: 'C. Melbourne',
    option_c_te: 'సి. మెల్బోర్న్',
    option_d_en: 'D. Perth',
    option_d_te: 'డి. పెర్త్',
    correct_option: 'B',
    explanation_en: 'Canberra is the national capital of Australia.',
    explanation_te: 'కాన్బెర్రా ఆస్ట్రేలియా జాతీయ రాజధాని.',
    difficulty: 'easy',
    visual,
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Prose sections of the contract.
// ─────────────────────────────────────────────────────────────────────────────

function buildQuestionSection(): string {
  const exampleJson = JSON.stringify(buildCanonicalQuestionExample(), null, 2)
  return [
    '',
    '## QUESTION OUTPUT FORMAT',
    '',
    'Return a single JSON array. Every element is ONE question object with EXACTLY these keys:',
    ...CANONICAL_QUESTION_FIELDS.map(f => `- ${f}`),
    '',
    'Example of one question object (without a visual). Replace the two placeholder',
    'topic values below with the EXACT topic names declared in the TOPIC IDENTITY',
    'section above — never reword them:',
    '',
    '```json',
    exampleJson,
    '```',
    '',
  ].join('\n')
}

function buildVisualSection(): string {
  const typeEnum = SUPPORTED_VISUAL_TYPES.map(t => `"${t}"`).join(' | ')
  const perType = VISUAL_TYPE_CONTRACTS.map(spec => {
    const example = JSON.stringify(buildVisualExample(spec.type), null, 2)
    return [
      `### ${spec.type}`,
      '',
      `${TITLE_PATTERN}`,
      spec.dataFields,
      '',
      '```json',
      example,
      '```',
      '',
    ].join('\n')
  }).join('\n')

  return [
    '',
    '## VISUAL CONTRACT',
    '',
    'A visual is used only when the question genuinely needs a table, chart, timeline, map, formula, or flow to reason correctly.',
    'Every visual object has EXACTLY this envelope:',
    '',
    '```json',
    '{ "type": ' + typeEnum + ', "title": "short heading" | null, "data": { ... } }',
    '```',
    '',
    `Whole visual size must stay under ${LIMITED.maxJsonBytes} bytes with nesting depth up to ${LIMITED.maxDepth}.`,
    'Per-type data shape:',
    '',
    perType,
    '',
    'VISUAL USE — NECESSITY GATE',
    'A visual MUST NOT be added merely because the topic supports visuals. It is included',
    'ONLY when it provides information the candidate genuinely needs to reason toward the',
    'answer. Before adding a visual, run ALL three checks:',
    '',
    '1. REMOVE TEST — if the question can still be answered confidently from ordinary',
    '   factual knowledge, the visual is unnecessary: set visual = null.',
    '2. ANSWER-LEAK TEST — does the visual directly display the answer (e.g. a ranked',
    '   list whose question asks for the rank, or a visual whose label IS the answer)?',
    '   If yes, reject the design and create a reasoning-based visual instead.',
    '3. INTERPRETATION TEST — must the candidate inspect, compare, calculate, infer,',
    '   sequence, classify or locate FROM the visual to solve? If no, do not add it.',
    '',
    'A decorative visual is never acceptable. Every visual must be educationally',
    'meaningful and relevant to the question; quality matters more than quantity, and a',
    'batch needs no predetermined number of visuals.',
    '',
    'VISUAL USE — REASONING EXAMPLES',
    'Good table: several sites/entities with multiple attributes; the question asks which',
    'conclusion, difference or ordering is best supported by comparing the rows/columns.',
    'Good chart: values whose percentage, difference, ratio or trend must be derived',
    'before an option can be chosen — the answer is never a chart label read directly.',
    'Good map: locations shown WITHOUT labelling the conclusion; the candidate infers the',
    'historical/geographic interpretation from the distribution. Good chronology: events',
    'and dates in a table; the candidate identifies a sequence or an interval.',
    '',
    'VISUAL TYPE SELECTION',
    'Choose the type that fits the reasoning (table, chart, map_overlay, geometry, venn,',
    'mermaid, latex or svg). Follow the visual opportunities named in the topic',
    'instructions; do NOT force svg, latex, geometry or venn merely because they are',
    'supported. A high-quality question without a visual beats a forced visual question.',
    '',
    'VISUAL EXPLANATION',
    'For a visual question, the explanation MUST state which information from the visual',
    'was used and how it leads to the answer. Never write "the visual shows the answer" —',
    'explain the comparison, calculation or inference instead.',
    '',
  ].join('\n')
}

function buildValidationSection(): string {
  return [
    '',
    '## VALIDATION RULES',
    '',
    'The mission: generate excellent competitive-exam questions from the topic-specific',
    'academic instructions — every question belongs to the same selected topic, every',
    'question is fully bilingual, and visuals exist only when the candidate must reason',
    'from them.',
    '',
    '1. Return ONLY a valid JSON array. No markdown code fences, no \u0060\u0060\u0060json wrapper, no conversational text.',
    '2. Use EXACTLY the key names above. Do not use older aliases such as `question`, `options`, or `correct`.',
    '3. `correct_option` must be exactly one of A, B, C or D.',
    '4. `difficulty` must be exactly easy, medium or hard.',
    '5. TOPIC IDENTITY: every question MUST carry the exact `topic_en` and `topic_te` declared for this' ,
    '   topic. The topic fields identify the Topic GROUP, never a subtopic: a question about a subtopic',
    '   (e.g. the Indus Valley Civilization under "Ancient Indian History") still carries the topic group',
    '   name. The two values MUST be byte-identical across the entire batch; never rename, shorten,',
    '   translate, paraphrase or "correct" them.',
    '6. BILINGUAL: when `topic_te` is non-null, EVERY question MUST fill question_text_te, option_a_te,',
    '   option_b_te, option_c_te, option_d_te and explanation_te — no null Telugu values. When the topic',
    '   has no Telugu name (`topic_te` null), the Telugu fields may be null or omitted.',
    '7. Telugu fields must be natural, grammatically correct, faithful translations that preserve the full',
    '   meaning and never add or omit information; Telugu options mirror their English counterparts exactly.',
    '8. QUALITY: prefer reasoning-based questions (comparison, chronology, cause/effect, application,',
    '   inference, multi-statement). Avoid recall-only trivia and isolated one-word-fact retrieval.',
    '9. NO ANSWER GIVEAWAYS: options must be similar in length, structure and style; the question wording,',
    '   option details, visual labels/title and explanation must never reveal the correct answer.',
    '10. VISUALS follow the VISUAL CONTRACT above: only when the candidate must reason from them, never',
    '    decorative, never displaying the answer, and their explanation states how the visual supports',
    '    the answer.',
    '11. NO DUPLICATE CONCEPTS: two questions testing the same fact, relationship, concept, chronology,',
    '    inference or comparison (even if reworded) are duplicates — keep an internal concept ledger.',
    '12. OPTIONS: exactly 4, one correct, three plausible distractors, no "All of the above" / "None of',
    '    the above". Spread correct answers across A/B/C/D naturally without a repeatable pattern.',
    '13. EXACT COUNT: generate EXACTLY the number of questions the topic instructions specify — never',
    '    fewer, never more. Count the array internally and correct the total before returning.',
    '14. DISTRIBUTIONS: percentage or ratio targets in the topic instructions must be converted to exact',
    '    INTEGER counts that sum to the required total. Topic coverage, difficulty, cognitive and',
    '    question-type allocations must each sum to that total and must not conflict.',
    '15. Never include exam_id, paper_id, subject_name, created_by, or any database field.',
    '16. Never reference the JSON key names as a separate text list outside the JSON array.',
    '',
  ].join('\n')
}

/** Compose the full canonical output contract block appended to topic prompts.
 *  Module-level memoized: the contract describes static system data. */
let cachedContract: string | null = null
export function buildCanonicalOutputContract(): string {
  if (cachedContract !== null) return cachedContract
  const contract = [
    '======================================================================',
    `${CONTRACT_AUTHORITY_PREFIX} v${VERSION} \u2014 AUTHORITY`,
    '======================================================================',
    '',
    'The topic instructions above define WHAT to generate. This section is the ONLY',
    'authority for HOW the output must be shaped. If the topic instructions above',
    'embed any other JSON schema, alias names, or visual shape, IGNORE that guidance:',
    'the keys, enums, and visual shapes in THIS section are the only ones accepted',
    'by the uploader.',
    buildQuestionSection(),
    buildVisualSection(),
    buildValidationSection(),
  ].join('\n')
  cachedContract = contract
  return contract
}

export interface ComposedContractInfo {
  text: string
  version: string
  visualTypes: readonly string[]
}

export function describeCanonicalOutputContract(): ComposedContractInfo {
  return {
    text: buildCanonicalOutputContract(),
    version: VERSION,
    visualTypes: SUPPORTED_VISUAL_TYPES,
  }
}