import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { composeBulkUploadPrompt } from './promptComposer'
import { buildCanonicalOutputContract, QUESTION_OUTPUT_CONTRACT_VERSION } from './dynamicOutputContract'
import { DYNAMIC_OUTPUT_CONTRACT_MARKER } from './dynamicOutputContractMarker'
import { sanitizeLegacyApplicationFormat } from './promptContentSanitizer'
import { BulkQuestionSchema } from '../../validations/questionSchema'

// Project-wide prompt corpus enforcement (42-section FINAL HARDENING).
//
// Source of truth for ALL 171 Admin Bulk Upload prompt_templates rows (the
// 33 repo-shipped bodies AND the 138 live-only bodies): the LATEST canonical
// storage migration (20260921000000_prompts_full_normalization.sql), whose
// UPDATE bodies are the final stored text a migrated database holds. Because
// the consolidated migration rewrites every live row to its canonical
// marker-bearing, token-free stored form, every corpus body generated by the
// runtime composer is assertable against the LITERAL stored bytes — a future
// edit to any body that reintroduces a legacy token or a second contract
// fails CI.

const MIGRATION_PATH = join(
  process.cwd(),
  'supabase',
  'migrations',
  '20260921000000_prompts_full_normalization.sql'
)

const FORBIDDEN_LEGACY_TOKENS = [
  'visual_engine',
  'render_type',
  'headers_en',
  'rows_en',
  'title_en',
  'title_te',
  'metadata',
  'diagram',
]

interface CorpusPrompt {
  id: string
  body: string
  md5: string
}

function loadCorpus(): CorpusPrompt[] {
  const sql = readFileSync(MIGRATION_PATH, 'utf8')
  const parts = sql.split('$rem$')
  const out: CorpusPrompt[] = []
  for (let i = 1; i + 1 < parts.length; i += 2) {
    const body = parts[i]
    const suffix = parts[i + 1]
    const idm = /WHERE id = '([0-9a-f-]+)'/.exec(suffix)
    const md5m = /AND md5\(prompt_text\) = '([0-9a-f]{32})'/.exec(suffix)
    if (idm) out.push({ id: idm[1], body, md5: md5m?.[1] ?? '' })
  }
  return out
}

function extractFenced(text: string): string[] {
  const re = /```(?:json)?\s*\n([\s\S]*?)\n```/g
  const out: string[] = []
  let m: RegExpExecArray | null
  while ((m = re.exec(text))) out.push(m[1])
  return out
}

function composedTokenFree(composed: string, label: string, tokens: string[]): void {
  for (const tok of tokens) {
    expect(composed, `${label}: composed prompt still contains "${tok}"`).not.toContain(tok)
  }
}

describe('Project-wide corpus: all 171 prompt_templates bodies', () => {
  let corpus: CorpusPrompt[]

  beforeAll(() => {
    corpus = loadCorpus()
  })

  it('loads exactly the 171 normalized bodies with md5 guards', () => {
    expect(corpus.length).toBe(171)
    expect(corpus.every(p => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(p.id))).toBe(true)
    expect(corpus.every(p => /^[0-9a-f]{32}$/.test(p.md5))).toBe(true)
  })

  it('the sanitizer fully cleanses every stored body of legacy tokens', () => {
    for (const p of corpus) {
      const clean = sanitizeLegacyApplicationFormat(p.body)
      composedTokenFree(clean, p.id, FORBIDDEN_LEGACY_TOKENS)
      // Academic content must survive the scrub — bodies are all multi-KB.
      expect(clean.length, `${p.id}: academic content must survive`).toBeGreaterThan(1000)
    }
  })

  it('every FINAL COMPOSED prompt: EXACTLY one canonical contract, no marker, zero legacy tokens', () => {
    const contractHeader = `CANONICAL OUTPUT CONTRACT v${QUESTION_OUTPUT_CONTRACT_VERSION}`
    for (const p of corpus) {
      const composed = composeBulkUploadPrompt(p.body, { topic_en: 'Sample Topic', topic_te: 'నమూనా అంశం' }).text
      expect((composed.match(/CANONICAL OUTPUT CONTRACT v/g) ?? []).length, `${p.id}: contract must appear exactly once`).toBe(1)
      expect(composed).toContain(contractHeader)
      expect(composed, `${p.id}: internal marker must never reach the AI`).not.toContain(DYNAMIC_OUTPUT_CONTRACT_MARKER)
      composedTokenFree(composed, p.id, FORBIDDEN_LEGACY_TOKENS)
    }
  })

  it('every composed prompt embeds the canonical contract BYTE-IDENTICAL exactly once', () => {
    const contractBlock = buildCanonicalOutputContract()
    for (const p of corpus) {
      const composed = composeBulkUploadPrompt(p.body).text
      expect(composed, `${p.id}: canonical contract bytes must be embedded verbatim`).toContain(contractBlock)
      expect((composed.match(/CANONICAL OUTPUT CONTRACT v/g) ?? []).length, `${p.id}: contract header exactly once`).toBe(1)
    }
  })

  it('the single taught schema = the canonical example and it parses through BulkQuestionSchema', () => {
    // The byte-identity assertion above proves every composed prompt teaches
    // exactly the contract's schema set (1 question example, 8 visual examples,
    // 1 envelope). Parsing the contract directly is therefore equivalent to
    // parsing any composed corpus prompt, without nested-fence ambiguity.
    const contractBlock = buildCanonicalOutputContract()
    const blocks = extractFenced(contractBlock).map(b => {
      try { return JSON.parse(b) as Record<string, unknown> } catch { return null }
    })
    const examples = blocks.filter(b => !!b && 'correct_option' in b)
    expect(examples.length).toBe(1)
    const r = BulkQuestionSchema.safeParse(examples[0]!)
    expect(r.success).toBe(true)
  })
})

describe('Multi-topic composition: LOBE identity distinct, contract byte-identical', () => {
  // One representative topic per mandated family (ancient history, early
  // medieval south-India dynasties, science, polity, economy, language, other).
  const TOPICS = [
    { topic_en: 'Ancient Indian History', topic_te: 'ప్రాచీన భారతదేశ చరిత్ర' },
    { topic_en: 'Early Medieval India and South Indian Dynasties', topic_te: 'ప్రారంభ మధ్యయుగ భారతదేశం మరియు దక్షిణ భారత రాజవంశాలు' },
    { topic_en: 'Indian Space Programme, ISRO', topic_te: 'భారత అంతరిక్ష కార్యక్రమం, ఇస్రో' },
    { topic_en: 'Indian Constitution', topic_te: 'భారత రాజ్యాంగం' },
    { topic_en: 'Indian Economy', topic_te: 'భారతీయ ఆర్థిక వ్యవస్థ' },
    { topic_en: 'Telugu Synonyms and Antonyms', topic_te: 'పర్యాయపదాలు మరియు వ్యతిరేక పదాలు' },
    { topic_en: 'Computer Knowledge for Bank Exams', topic_te: 'బ్యాంకు పరీక్షలకు కంప్యూటర్ జ్ఞానం' },
  ]
  const BASE_BODY = '# Representative topic syllabus\nGenerate exactly 10 MCQs.'

  const composedFor = (t: { topic_en: string; topic_te: string }): string =>
    composeBulkUploadPrompt(BASE_BODY, t).text

  it('injects a distinct TOPIC IDENTITY block per topic', () => {
    for (const t of TOPICS) {
      const composed = composedFor(t)
      expect(composed).toContain('## TOPIC IDENTITY')
      expect(composed).toContain(`topic_en = "${t.topic_en}"`)
      expect(composed).toContain(`topic_te = "${t.topic_te}"`)
    }
    const identities = TOPICS.map(t => `topic_en = "${t.topic_en}"`)
    expect(new Set(identities).size).toBe(TOPICS.length)
  })

  it('produces a BYTE-IDENTICAL canonical contract across all topics', () => {
    const contracts = TOPICS.map(t => {
      const composed = composedFor(t)
      const at = composed.indexOf('CANONICAL OUTPUT CONTRACT v')
      expect(at).toBeGreaterThan(0)
      return composed.slice(at)
    })
    expect(new Set(contracts).size).toBe(1)
  })

  it('the polity topic composes WITHOUT the old cross-topic example bytes', () => {
    const pol = TOPICS[3]
    const composed = composedFor(pol)
    expect(composed).not.toContain('Polity Basics')
    expect(composed).not.toContain('Ambedkar')
    expect(composed).not.toContain('architect of the Indian Constitution')
  })

  it('the contract example is topic-neutral (placeholder topic names)', () => {
    const composed = composedFor(TOPICS[0])
    expect(composed).toContain('"topic_en": "<COPY topic_en VERBATIM>"')
    expect(composed).toContain('"topic_te": "<COPY topic_te VERBATIM>"')
    for (const t of TOPICS.slice(1)) {
      const c = composedFor(t)
      expect(c).toContain('"topic_en": "<COPY topic_en VERBATIM>"')
    }
  })
})